### ISSUE TITLE
Tour consumer interface

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/Camino#25]
- better interface on non-phones
- new look and feel
- Theming / styling
 - can we have a couple themes to choose from?
 - can creators modify them?

**Comment by jxjj** [comment]
First WIP prototype on <https://github.com/UMN-LATIS/Camino/tree/feature/prototype-new-tour-interface>.

Feedback from testing:
- [ ] swipe to right/left to a new stop and have that be the active card. Preview cards is a very limited use card.
- [ ] get a little more space for card content. Right now, it's pretty narrow. Maybe decrease padding on card and gaps between cards. (Or maybe full screen mode?)
- [ ] when stop nav expands, it shouldn't be full screen. 
- [ ] Make the fact that I can swipe to next/prev card more obvious. More apparent that there's a card? Add arrows to hint?
- [ ] Global nav items need more grounding. Either make floating circle buttons, or add a top bar.
- [ ] When user scrolls down and the stop title and number disappears from view, pin this information to the top in a sticky header?
- [ ] Bottom nav numbers may be a bit too squished if there are quite a few stops. Show progress with dots (or something else) once numbers are too crowded.
- [ ] The stop nav should expand when tapping anything in that space. Not just tapping the expand button.  No need to have the numbers be tappable.
- [ ] Add main menu system with Home, Help, Language/Settings, Report a Problem.
- [ ] Add continue button at bottom of card to make next steps more obvious.
- [ ] Map button should open Map modal
- [ ] Swiping back to dismiss modal?

Other convo:
- [ ] Remove Tailwind.
- [ ] Consider moving`tour` prop to Vuex to avoid prop drilling.
- [ ] Consider creating a separate folder for all js/scss for tour editor - keeping tour taker app separate.

@cmcfadden - Thanks for the feedback. Anything else I'm missed?
